//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cim_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cim_t()
        {
            this.ORE_t = new HashSet<ORE_t>();
            this.Regio_t = new HashSet<Regio_t>();
        }
    
        public int Cid { get; set; }
        public Nullable<int> Iranyitoszam { get; set; }
        public Nullable<int> KozteruletId { get; set; }
        public Nullable<int> Hazszam1 { get; set; }
        public string Hazszamtores1 { get; set; }
        public Nullable<int> Hazszam2 { get; set; }
        public string Hazszamtores2 { get; set; }
        public string Epuletjel { get; set; }
        public string Epulettores { get; set; }
        public string Lepcsohaz { get; set; }
        public string Emelet { get; set; }
        public string Ajto { get; set; }
        public string Ajtotores { get; set; }
        public string HRSZ { get; set; }
        public string HRSZ1 { get; set; }
        public string HRSZ2 { get; set; }
        public string HRSZ3 { get; set; }
        public string Forras { get; set; }
        public string EgyediCim { get; set; }
        public bool Ervenyes { get; set; }
        public System.DateTime UtolsoModositasDatuma { get; set; }
        public int UtolsoModositoId { get; set; }
        public Nullable<System.DateTime> EllenorzesDatuma { get; set; }
        public Nullable<int> EllenorzoId { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> Old_TavirCimid { get; set; }
        public Nullable<int> Old_TavirUtcakod { get; set; }
        public Nullable<int> Old_TavirVaroskod { get; set; }
        public string CimFilterMask { get; set; }
        public string EmeletJelKod { get; set; }
    
        public virtual Munkatars_t Munkatars_t { get; set; }
        public virtual Munkatars_t Munkatars_t1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORE_t> ORE_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regio_t> Regio_t { get; set; }
        public virtual EmeletJel_m EmeletJel_m { get; set; }
        public virtual Kozterulet_t Kozterulet_t { get; set; }
    }
}
