//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kozterulet_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kozterulet_t()
        {
            this.Cim_t = new HashSet<Cim_t>();
        }
    
        public int KozteruletId { get; set; }
        public int TelepulesId { get; set; }
        public int IRSZ { get; set; }
        public string Nev { get; set; }
        public string NevRegi { get; set; }
        public string KozteruletJellegKod { get; set; }
        public string Varosresz { get; set; }
        public Nullable<int> Szam1 { get; set; }
        public string Jel1 { get; set; }
        public Nullable<int> Szam2 { get; set; }
        public string Jel2 { get; set; }
        public string Kerulet { get; set; }
        public string Telepulesresz { get; set; }
        public string DijbeszedoNev { get; set; }
        public string FoldhivatalNev { get; set; }
        public Nullable<int> Old_TavirUtcakod { get; set; }
        public string Megjegyzes { get; set; }
        public string Forras { get; set; }
        public System.DateTime UtolsoModositasDatuma { get; set; }
        public int UtolsoModositoId { get; set; }
        public Nullable<System.DateTime> EllenorzesDatuma { get; set; }
        public Nullable<int> EllenorzoId { get; set; }
        public byte[] Version { get; set; }
        public bool Ervenyes { get; set; }
        public bool Minositett_torzsadat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cim_t> Cim_t { get; set; }
        public virtual Munkatars_t Munkatars_t { get; set; }
        public virtual KozteruletJelleg_m KozteruletJelleg_m { get; set; }
        public virtual Munkatars_t Munkatars_t1 { get; set; }
    }
}
