//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesterkorzet_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesterkorzet_t()
        {
            this.Munkatars_t1 = new HashSet<Munkatars_t>();
        }
    
        public int MesterkorzetId { get; set; }
        public string Nev { get; set; }
        public Nullable<int> VezetoId { get; set; }
        public int RegioId { get; set; }
        public Nullable<double> ProduktivitasiKorekcio { get; set; }
        public byte[] Version { get; set; }
    
        public virtual Munkatars_t Munkatars_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munkatars_t> Munkatars_t1 { get; set; }
        public virtual Regio_t Regio_t { get; set; }
    }
}
