//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class MunkaTargya_cs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MunkaTargya_cs()
        {
            this.MunkaTargyaHiba_t = new HashSet<MunkaTargyaHiba_t>();
        }
    
        public int MunkaTargyaId { get; set; }
        public int MunkaId { get; set; }
        public Nullable<int> TanusitvanyId { get; set; }
        public Nullable<int> Kid { get; set; }
        public Nullable<int> OsszekotoelemId { get; set; }
        public Nullable<int> TuzeloberendezesId { get; set; }
        public Nullable<int> Oid { get; set; }
        public bool Potdijkoteles { get; set; }
        public byte[] Version { get; set; }
        public string MunkaTargyaTipusKod { get; set; }
        public bool Zart { get; set; }
        public string KemenyJelKod { get; set; }
        public bool UtolsoSormunkavegzesDatumaIrodjon { get; set; }
        public bool UtolsoMuszakiFelulvizsgalatDatumaIrodjon { get; set; }
        public Nullable<double> COMeresEredmeny { get; set; }
        public bool ReszbenZart { get; set; }
        public string Megjegyzes { get; set; }
        public Nullable<int> Eid { get; set; }
    
        public virtual Munka_t Munka_t { get; set; }
        public virtual ORE_t ORE_t { get; set; }
        public virtual Tanusitvany_t Tanusitvany_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MunkaTargyaHiba_t> MunkaTargyaHiba_t { get; set; }
    }
}
