//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regio_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regio_t()
        {
            this.Mesterkorzet_t = new HashSet<Mesterkorzet_t>();
            this.Munkatars_t = new HashSet<Munkatars_t>();
            this.Rendeles_t = new HashSet<Rendeles_t>();
        }
    
        public int RegioId { get; set; }
        public string Nev { get; set; }
        public Nullable<int> Cid { get; set; }
        public string Telefon { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> VezetoId { get; set; }
        public string RegioKod { get; set; }
        public bool KeszenletiCsoport { get; set; }
        public string CimSzoveg { get; set; }
        public string Email { get; set; }
    
        public virtual Cim_t Cim_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mesterkorzet_t> Mesterkorzet_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munkatars_t> Munkatars_t { get; set; }
        public virtual Munkatars_t Munkatars_t1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles_t> Rendeles_t { get; set; }
    }
}
