//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendeles_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rendeles_t()
        {
            this.Munka_t = new HashSet<Munka_t>();
        }
    
        public int RendelesId { get; set; }
        public string Rendelesszam { get; set; }
        public string RendelesStatuszKod { get; set; }
        public Nullable<int> Iid { get; set; }
        public Nullable<int> Eid { get; set; }
        public Nullable<int> Oid { get; set; }
        public string MunkaTipusKod { get; set; }
        public bool Szamlazando { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> SzamlazasraAtadas { get; set; }
        public Nullable<System.DateTime> Kiszamlazva { get; set; }
        public Nullable<int> MegrendeloId { get; set; }
        public Nullable<int> ErtesitendoSzemelyId { get; set; }
        public Nullable<int> TervezoId { get; set; }
        public Nullable<System.DateTime> RendelesFelvetelDatuma { get; set; }
        public Nullable<int> KivitelezoId { get; set; }
        public string SzamlazoRendszerKod { get; set; }
        public int MunkatVegzoRegioId { get; set; }
        public Nullable<System.DateTime> JovahagyasDatuma { get; set; }
        public Nullable<int> JovahagyoId { get; set; }
        public bool NyilatkozatKotelezo { get; set; }
        public bool KellNyilatkozat { get; set; }
        public bool EpuletUtolsoSormunkavegzesDatumaIrodjon { get; set; }
        public bool EpuletUtolsoMuszakiFelulvizsgalatDatumaIrodjon { get; set; }
        public Nullable<int> TajekoztatoId { get; set; }
        public Nullable<System.DateTime> SzamlazasDatumaTan { get; set; }
        public Nullable<System.DateTime> RendelesBeerkezesDatuma { get; set; }
        public Nullable<System.DateTime> kacs_SzamlazvaVisszajelzesTan { get; set; }
        public Nullable<bool> kacs_2014SormunkaPotmunkaja { get; set; }
        public Nullable<bool> kacs_DuplaRendelesRogzitesEllenorizve { get; set; }
        public Nullable<System.DateTime> kacs_EmailkeresDatum { get; set; }
        public string kacs_EmailkeresSzovegKod { get; set; }
        public string kacs_EmailkeresEredmeny { get; set; }
        public Nullable<System.DateTime> kacs_SmskeresDatum { get; set; }
        public string kacs_SmskeresSzovegKod { get; set; }
        public string kacs_SmskeresEredmeny { get; set; }
        public Nullable<bool> kacs_KeziSzamlazasTiltott { get; set; }
        public string kacs_NemszamlazandoIndoklas { get; set; }
        public Nullable<bool> kacs_NemszamlazandoJogos { get; set; }
        public Nullable<int> ElszamolasEve { get; set; }
        public Nullable<bool> LakossagiAr { get; set; }
        public Nullable<int> SzlafizPartnerId { get; set; }
        public string SzlafizGazdformcsopKod { get; set; }
        public bool kacs_NincsSzamlazhatoMunkatargyaRendben { get; set; }
        public Nullable<System.DateTime> TeljesitesDatuma { get; set; }
        public string SzamlazasUtolsoKvhHibakod { get; set; }
    
        public virtual Munkatars_t Munkatars_t { get; set; }
        public virtual ORE_t ORE_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Munka_t> Munka_t { get; set; }
        public virtual RendelesStatusz_m RendelesStatusz_m { get; set; }
        public virtual Regio_t Regio_t { get; set; }
    }
}
