//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanusitvany2015FO
    {
        public string EpuletID { get; set; }
        public string hrsztan { get; set; }
        public string Vonalkod { get; set; }
        public string Kirnev { get; set; }
        public string Kircim { get; set; }
        public string IdHaszn { get; set; }
        public string Ingatlancim { get; set; }
        public string TulajdonosNev { get; set; }
        public string TulajdonosCim { get; set; }
        public string Használónév { get; set; }
        public string HasználóCím { get; set; }
        public Nullable<int> MuszakiEv { get; set; }
        public string KezelőNév { get; set; }
        public string KezelőCím { get; set; }
        public string KezelőEmail { get; set; }
        public string KezelőTelefon { get; set; }
        public string Jel01 { get; set; }
        public Nullable<int> Db01 { get; set; }
        public string Jel02 { get; set; }
        public Nullable<int> Db02 { get; set; }
        public string Jel03 { get; set; }
        public Nullable<int> Db03 { get; set; }
        public string Jel04 { get; set; }
        public Nullable<int> Db04 { get; set; }
        public string Jel05 { get; set; }
        public Nullable<int> Db05 { get; set; }
        public string Jel06 { get; set; }
        public Nullable<int> Db06 { get; set; }
        public Nullable<double> fmszint06 { get; set; }
        public string Jel07 { get; set; }
        public Nullable<int> Db07 { get; set; }
        public Nullable<double> fmszint07 { get; set; }
        public string Jel08 { get; set; }
        public Nullable<int> Db08 { get; set; }
        public Nullable<double> fmszint08 { get; set; }
        public string Jel09 { get; set; }
        public Nullable<int> Db09 { get; set; }
        public Nullable<double> fmszint09 { get; set; }
        public string Jel10 { get; set; }
        public Nullable<int> Db10 { get; set; }
        public Nullable<double> fmszint10 { get; set; }
        public int Eid { get; set; }
        public int Iid { get; set; }
        public int EIDnbelüliFotan { get; set; }
        public Nullable<System.DateTime> TervezettMunkavegzesDatuma { get; set; }
        public Nullable<int> RegioID { get; set; }
        public Nullable<int> Kemenyseproparid { get; set; }
        public string Kemenyseproparnev { get; set; }
        public Nullable<int> Munkavegzeshonapja { get; set; }
        public string Sorrend { get; set; }
        public Nullable<int> TervezesiegysegID { get; set; }
        public Nullable<int> TervezesiegysegCsoportID { get; set; }
        public Nullable<System.DateTime> NyomdabaadasDatuma { get; set; }
        public Nullable<int> EpuletOREMennyisegTenyleges { get; set; }
        public Nullable<int> MesterkorzetId { get; set; }
        public Nullable<int> Ev { get; set; }
    }
}
