//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanusitvany2015ORE
    {
        public string Epuletid { get; set; }
        public string OREVonalkod { get; set; }
        public string Kirnev { get; set; }
        public string Kircim { get; set; }
        public string Ingatlancim { get; set; }
        public Nullable<int> EpuletOREMennyisegTenyleges { get; set; }
        public int eid { get; set; }
        public int iid { get; set; }
        public Nullable<System.DateTime> TervezettMunkavegzesDatuma { get; set; }
        public Nullable<int> RegioID { get; set; }
        public Nullable<int> Kemenyseproparid { get; set; }
        public string Kemenyseproparnev { get; set; }
        public Nullable<int> MunkavegzesHonapja { get; set; }
        public string FotanusitvanyVonalkod { get; set; }
        public string Sorrend { get; set; }
        public Nullable<int> TervezesiegysegID { get; set; }
        public Nullable<int> TervezesiegysegCsoportID { get; set; }
        public Nullable<System.DateTime> NyomdabaadasDatuma { get; set; }
        public Nullable<int> MesterkorzetId { get; set; }
        public Nullable<int> Ev { get; set; }
    }
}
