//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanusitvany_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tanusitvany_t()
        {
            this.Tanusitvany_t1 = new HashSet<Tanusitvany_t>();
            this.MunkaTargya_cs = new HashSet<MunkaTargya_cs>();
        }
    
        public int TanusitvanyId { get; set; }
        public Nullable<int> SzulotanusitvanyId { get; set; }
        public Nullable<int> MunkaId { get; set; }
        public string Vonalkod { get; set; }
        public string NyomtatvanyTipusKod { get; set; }
        public Nullable<int> Oid { get; set; }
        public string Dokumentum { get; set; }
        public Nullable<System.DateTime> BeolvasasIdopontja { get; set; }
        public Nullable<int> BeolvasoId { get; set; }
        public Nullable<int> AtvevoId { get; set; }
        public bool Sormunka1 { get; set; }
        public bool Sormunka2 { get; set; }
        public bool Zart { get; set; }
        public bool Elvegzett { get; set; }
        public bool Bianko { get; set; }
        public byte[] Version { get; set; }
        public bool Technikai { get; set; }
        public Nullable<System.DateTime> KiallitasIdopontja { get; set; }
        public Nullable<int> KiallitoId { get; set; }
        public string kacs_Megjegyzes { get; set; }
        public bool GazElzarasahozHozzajarult { get; set; }
        public string Megjegyzes { get; set; }
        public bool Ketszerzart { get; set; }
        public bool EvesEllenorzesIndokolt { get; set; }
        public string Tulajdonos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tanusitvany_t> Tanusitvany_t1 { get; set; }
        public virtual Tanusitvany_t Tanusitvany_t2 { get; set; }
        public virtual Munkatars_t Munkatars_t { get; set; }
        public virtual Munkatars_t Munkatars_t1 { get; set; }
        public virtual NyomtatvanyTipus_m NyomtatvanyTipus_m { get; set; }
        public virtual ORE_t ORE_t { get; set; }
        public virtual Munka_t Munka_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MunkaTargya_cs> MunkaTargya_cs { get; set; }
    }
}
