//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCim
    {
        public int Cid { get; set; }
        public Nullable<int> Iranyitoszam { get; set; }
        public string TelepulesNev { get; set; }
        public string KozteruletNev { get; set; }
        public string KozteruletJellegNev { get; set; }
        public Nullable<int> Hazszam1 { get; set; }
        public string Hazszamtores1 { get; set; }
        public Nullable<int> Hazszam2 { get; set; }
        public string Hazszamtores2 { get; set; }
        public string Epuletjel { get; set; }
        public string Epulettores { get; set; }
        public string Lepcsohaz { get; set; }
        public string Emelet { get; set; }
        public string Ajto { get; set; }
        public string Ajtotores { get; set; }
        public string CimSzoveg { get; set; }
        public string CimHRSZ { get; set; }
        public string UtcaHazszam { get; set; }
        public string Hazszam { get; set; }
        public string EpuletSzoveg { get; set; }
        public string LhSzoveg { get; set; }
        public string AjtoSzoveg { get; set; }
        public string HazszamSzoveg { get; set; }
        public string EmeletKod { get; set; }
        public Nullable<int> KozteruletId { get; set; }
        public string CimSzovegEpulet { get; set; }
    }
}
