//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEpuletElsCim
    {
        public int Eid { get; set; }
        public int Cid { get; set; }
        public Nullable<int> IRSZ { get; set; }
        public string CimSzoveg { get; set; }
        public Nullable<int> Iid { get; set; }
        public string CimHRSZ { get; set; }
        public string EpHRSZ { get; set; }
        public string UtcaHazszam { get; set; }
        public string TelepulesNev { get; set; }
    }
}
