//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class VonalkodTartomany_t
    {
        public string Kod { get; set; }
        public string Nev { get; set; }
        public string Eleje { get; set; }
        public string Vege { get; set; }
        public string NyomtatvanytipusKod { get; set; }
        public byte[] Version { get; set; }
        public string Prefix { get; set; }
        public string KarakterKod { get; set; }
        public Nullable<int> KioszthatoSorszam { get; set; }
        public Nullable<int> Ev { get; set; }
    
        public virtual NyomtatvanyTipus_m NyomtatvanyTipus_m { get; set; }
    }
}
