//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOreTulaj1
    {
        public int Oid { get; set; }
        public int Eid { get; set; }
        public bool OreTorolve { get; set; }
        public int OreTulajId { get; set; }
        public string OreTulajNev { get; set; }
        public string OreTulajCimSzoveg { get; set; }
        public string OreTulajGazdformcsopKod { get; set; }
        public string OreTulajGazdformcsopNev { get; set; }
        public string OreTulajDB_Partnerid { get; set; }
    }
}
