//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vonalkod
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOreCim
    {
        public int Oid { get; set; }
        public int Cid { get; set; }
        public string Lepcsohaz { get; set; }
        public string Emelet { get; set; }
        public string EmeletJelKod { get; set; }
        public string Ajto { get; set; }
        public string Ajtotores { get; set; }
        public Nullable<int> IRSZ { get; set; }
        public string Cimszoveg { get; set; }
        public int eid { get; set; }
        public int iid { get; set; }
        public string OreHRSZ { get; set; }
        public string CimHRSZ { get; set; }
        public string UtcaHazszam { get; set; }
        public string TelepulesNev { get; set; }
    }
}
